export const LOCATE_USER = 'LOCATE_USER';
export const LOCATE_USER_START = 'LOCATE_USER_START';
export const LOCATE_USER_SUCCESS = 'LOCATE_USER_SUCCESS';
export const LOCATE_USER_FAIL = 'LOCATE_USER_FAIL'
// export const SET_LOCATION = 'SET_LOCATION'

export const SEARCH_CITY = 'SEARCH_CITY ';
export const SEARCH_CITY_START = 'SEARCH_CITY_START';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';

export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
